# Generated by Django 2.0.4 on 2018-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=250)),
                ('bio', models.CharField(max_length=250)),
                ('git_hub', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('graduation_date', models.DateField()),
            ],
        ),
    ]
