# Generated by Django 2.0.4 on 2018-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('graduation_date', models.DateField()),
                ('photo', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('website_url', models.CharField(max_length=50)),
            ],
        ),
    ]
