language:
  - python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - DJANGO=2.0.5
    - DJANGO_DEBUG=False

# before_install:

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - psql -c 'CREATE DATABASE talent_roster_test;' -U postgres
  - python manage.py syncdb --noinput

script:
  - python manage.py test
